<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Penjualan;

class PenjualanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $penjualans = [
            [
                'created_date' => '2026-01-12',
                'created_time' => '10:30:00',
                'order_no' => 'ORD001',
                'receipt_no' => 'RCP001',
                'invoice_reference' => 'INV001',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'PMT001',
                'article_name' => 'Pearl Milk Tea',
                'quantity' => 2,
                'original_price' => 25000.00,
                'net_price' => 25000.00,
                'promotion_amount' => 0.00,
                'promotion_code' => null,
                'promotion_name' => null,
                'promotion_channel' => null,
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'TEA001',
                'commodity_name' => 'Tea Based',
                'merchandise_code' => 'MTC001',
                'merchandise_name' => 'Milk Tea Category',
                'product_group_code' => 'PMT001',
                'product_group_name' => 'Pearl Milk Tea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '10:45:00',
                'order_no' => 'ORD001',
                'receipt_no' => 'RCP001',
                'invoice_reference' => 'INV001',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'BSM001',
                'article_name' => 'Brown Sugar Fresh Milk',
                'quantity' => 1,
                'original_price' => 28000.00,
                'net_price' => 28000.00,
                'promotion_amount' => 0.00,
                'promotion_code' => null,
                'promotion_name' => null,
                'promotion_channel' => null,
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'MLK001',
                'commodity_name' => 'Milk Based',
                'merchandise_code' => 'FSM001',
                'merchandise_name' => 'Fresh Milk Category',
                'product_group_code' => 'BSM001',
                'product_group_name' => 'Brown Sugar Series',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '11:00:00',
                'order_no' => 'ORD002',
                'receipt_no' => 'RCP002',
                'invoice_reference' => 'INV002',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'CPK001',
                'article_name' => 'Chicken Popcorn',
                'quantity' => 1,
                'original_price' => 15000.00,
                'net_price' => 13500.00,
                'promotion_amount' => 1500.00,
                'promotion_code' => 'PROMO10',
                'promotion_name' => '10% Off Snacks',
                'promotion_channel' => 'In-Store',
                'department_code' => 'FD001',
                'department_name' => 'Food',
                'commodity_code' => 'CKN001',
                'commodity_name' => 'Chicken Products',
                'merchandise_code' => 'SNK001',
                'merchandise_name' => 'Snacks Category',
                'product_group_code' => 'CPK001',
                'product_group_name' => 'Chicken Popcorn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '11:15:00',
                'order_no' => 'ORD002',
                'receipt_no' => 'RCP002',
                'invoice_reference' => 'INV002',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'FFR001',
                'article_name' => 'French Fries',
                'quantity' => 2,
                'original_price' => 12000.00,
                'net_price' => 12000.00,
                'promotion_amount' => 0.00,
                'promotion_code' => null,
                'promotion_name' => null,
                'promotion_channel' => null,
                'department_code' => 'FD001',
                'department_name' => 'Food',
                'commodity_code' => 'POT001',
                'commodity_name' => 'Potato Products',
                'merchandise_code' => 'SNK001',
                'merchandise_name' => 'Snacks Category',
                'product_group_code' => 'FFR001',
                'product_group_name' => 'French Fries',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '11:30:00',
                'order_no' => 'ORD003',
                'receipt_no' => 'RCP003',
                'invoice_reference' => null,
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'TQT001',
                'article_name' => 'Taro QQ',
                'quantity' => 1,
                'original_price' => 30000.00,
                'net_price' => 30000.00,
                'promotion_amount' => 0.00,
                'promotion_code' => null,
                'promotion_name' => null,
                'promotion_channel' => null,
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'TEA001',
                'commodity_name' => 'Tea Based',
                'merchandise_code' => 'FRZ001',
                'merchandise_name' => 'Frozen Category',
                'product_group_code' => 'TQT001',
                'product_group_name' => 'Taro QQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '11:45:00',
                'order_no' => 'ORD004',
                'receipt_no' => 'RCP004',
                'invoice_reference' => 'INV004',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'MCG001',
                'article_name' => 'Matcha Cheese Foam',
                'quantity' => 1,
                'original_price' => 35000.00,
                'net_price' => 31500.00,
                'promotion_amount' => 3500.00,
                'promotion_code' => 'CHEESE10',
                'promotion_name' => '10% Off Cheese Series',
                'promotion_channel' => 'Mobile App',
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'TEA001',
                'commodity_name' => 'Tea Based',
                'merchandise_code' => 'CHS001',
                'merchandise_name' => 'Cheese Foam Category',
                'product_group_code' => 'MCG001',
                'product_group_name' => 'Matcha Cheese Foam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '12:00:00',
                'order_no' => 'ORD005',
                'receipt_no' => 'RCP005',
                'invoice_reference' => 'INV005',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'CHM001',
                'article_name' => 'Chocolate Milk Tea',
                'quantity' => 2,
                'original_price' => 26000.00,
                'net_price' => 26000.00,
                'promotion_amount' => 0.00,
                'promotion_code' => null,
                'promotion_name' => null,
                'promotion_channel' => null,
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'TEA001',
                'commodity_name' => 'Tea Based',
                'merchandise_code' => 'MTC001',
                'merchandise_name' => 'Milk Tea Category',
                'product_group_code' => 'CHM001',
                'product_group_name' => 'Chocolate Milk Tea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '12:15:00',
                'order_no' => 'ORD006',
                'receipt_no' => 'RCP006',
                'invoice_reference' => null,
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'OGT001',
                'article_name' => 'Original Thai Tea',
                'quantity' => 1,
                'original_price' => 22000.00,
                'net_price' => 22000.00,
                'promotion_amount' => 0.00,
                'promotion_code' => null,
                'promotion_name' => null,
                'promotion_channel' => null,
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'TEA001',
                'commodity_name' => 'Tea Based',
                'merchandise_code' => 'THI001',
                'merchandise_name' => 'Thai Tea Category',
                'product_group_code' => 'OGT001',
                'product_group_name' => 'Original Thai Tea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '12:30:00',
                'order_no' => 'ORD007',
                'receipt_no' => 'RCP007',
                'invoice_reference' => 'INV007',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'HBT001',
                'article_name' => 'Honey Bubble Tea',
                'quantity' => 1,
                'original_price' => 24000.00,
                'net_price' => 21600.00,
                'promotion_amount' => 2400.00,
                'promotion_code' => 'HONEY10',
                'promotion_name' => '10% Off Honey Series',
                'promotion_channel' => 'In-Store',
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'TEA001',
                'commodity_name' => 'Tea Based',
                'merchandise_code' => 'BBL001',
                'merchandise_name' => 'Bubble Tea Category',
                'product_group_code' => 'HBT001',
                'product_group_name' => 'Honey Bubble Tea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_date' => '2026-01-12',
                'created_time' => '12:45:00',
                'order_no' => 'ORD008',
                'receipt_no' => 'RCP008',
                'invoice_reference' => 'INV008',
                'void' => false,
                'site_code' => 'CGI01',
                'site_description' => 'Chatime Grand Indonesia',
                'article_code' => 'RSB001',
                'article_name' => 'Red Bean Smoothie',
                'quantity' => 1,
                'original_price' => 32000.00,
                'net_price' => 32000.00,
                'promotion_amount' => 0.00,
                'promotion_code' => null,
                'promotion_name' => null,
                'promotion_channel' => null,
                'department_code' => 'BEV001',
                'department_name' => 'Beverages',
                'commodity_code' => 'SMO001',
                'commodity_name' => 'Smoothies',
                'merchandise_code' => 'SMO001',
                'merchandise_name' => 'Smoothie Category',
                'product_group_code' => 'RSB001',
                'product_group_name' => 'Red Bean Smoothie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Penjualan::insert($penjualans);
    }
}
